/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainbar.java
 *
 * Created on Jan 29, 2012, 8:25:41 PM
 */
/**
 *
 * @author Xhesina Ismaili
    */
import javax.swing.*;
import java.util.*;
import java.text.*;
import java.io.*;
public class mainbar extends javax.swing.JFrame {

    /** Creates new form mainbar */
     
    private static ArrayList<Table> tablelist = new ArrayList();
    private static ArrayList<Waiter> waiterlist = new ArrayList();
    private static ArrayList<Manager> managerlist = new ArrayList();
    private static ArrayList<Item> itemlist = new ArrayList();
    private Item items;
    private Waiter currentuser;
    private Table currenttable;
    

    public int login(String u, String p)
    {

        for (Waiter wait : waiterlist)
        {
            if((wait.getUsername().equals(u) && wait.getPassword().equals(p)))
            {
                currentuser = wait;
                return 1;
            }
        }
        
        return 0;
    }
    
    public int totalnumberoftables()
    {
        int n = 0;
        for(Table tab : tablelist)
        {
            if(tab.getUser().getUsername().equals(currentuser.getUsername()))
                 n++;
        }
        return n;
    }
    
    public double totalamountofalltables()
    {
        double amount = 0.0;
        for(Table tab : tablelist)
        {
            if(tab.getUser().getUsername().equals(currentuser.getUsername()))
                amount = amount + tab.getTotalAmount();
        }
        return amount;
    }
    
    private void hideAllFrames(){
        helpInternalFrame.setVisible(false);
        tableInternalFrame.setVisible(false);
        PrintInfoInternalFrame.setVisible(false);
    }
    public mainbar()
    {
        
        Waiter w1 = new Waiter(1234,"kini","file","shpi",124);
        
        waiterlist.add(w1);
        
        Item i1 = new Item("coca cola",2);
        Item i2 = new Item("sprite",2);
        Item i3 = new Item("redbull",2.5);
        Item i4 = new Item("johnny",4);
        Item i5 = new Item("corona",3.5);
        Item i6 = new Item("ice tea",2);
        
        itemlist.add(i1);
        itemlist.add(i2);
        itemlist.add(i3);
        itemlist.add(i4);
        itemlist.add(i5);
        itemlist.add(i6);
        
        initComponents();
        setSize(500,500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tableInternalFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tableid = new javax.swing.JTextField();
        tabletype = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        numberofitems = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        additem = new javax.swing.JMenuItem();
        removeitem = new javax.swing.JMenuItem();
        addcustomer = new javax.swing.JMenu();
        simplecustomer = new javax.swing.JMenuItem();
        companycustomer = new javax.swing.JMenuItem();
        customeremployee = new javax.swing.JMenuItem();
        loyalcustomer = new javax.swing.JMenuItem();
        tableinfo = new javax.swing.JMenu();
        helpInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AdditemInternalFrame = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        itemprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        itemtypecombo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        itemname = new javax.swing.JTextField();
        removeitemInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsintable = new javax.swing.JList();
        Removeitem = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PrintInfoInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        waiterinfo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        tableEmployeeMenuItem = new javax.swing.JMenuItem();
        tableCompanyMenuItem = new javax.swing.JMenuItem();
        tableFidelityMenuItem = new javax.swing.JMenuItem();
        simpletable = new javax.swing.JMenuItem();
        numberoftables = new javax.swing.JMenuItem();
        totalamount = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        DataMenu = new javax.swing.JMenu();
        load = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        PrintInfoMenu = new javax.swing.JMenu();
        ExitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentHidden(evt);
            }
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentMoved(evt);
            }
        });

        jLabel1.setText("Table Id");

        jLabel2.setText("Table type");

        jLabel3.setText("Time");

        jLabel4.setText("Number of items");

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableid.setEditable(false);

        tabletype.setEditable(false);

        time.setEditable(false);
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        numberofitems.setEditable(false);

        jMenu1.setText("File");

        additem.setText("Add item");
        additem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemActionPerformed(evt);
            }
        });
        jMenu1.add(additem);

        removeitem.setText("Remove item");
        removeitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemActionPerformed(evt);
            }
        });
        jMenu1.add(removeitem);

        addcustomer.setText("Add customer");

        simplecustomer.setText("Simple customer");
        addcustomer.add(simplecustomer);

        companycustomer.setText("Company customer");
        addcustomer.add(companycustomer);

        customeremployee.setText("Customer Employee");
        addcustomer.add(customeremployee);

        loyalcustomer.setText("Loyal Customer");
        addcustomer.add(loyalcustomer);

        jMenu1.add(addcustomer);

        jMenuBar2.add(jMenu1);

        tableinfo.setText("Table info");
        tableinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableinfoMousePressed(evt);
            }
        });
        tableinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableinfoActionPerformed(evt);
            }
        });
        jMenuBar2.add(tableinfo);

        tableInternalFrame.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout tableInternalFrameLayout = new javax.swing.GroupLayout(tableInternalFrame.getContentPane());
        tableInternalFrame.getContentPane().setLayout(tableInternalFrameLayout);
        tableInternalFrameLayout.setHorizontalGroup(
            tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableInternalFrameLayout.createSequentialGroup()
                .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableInternalFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numberofitems)
                            .addComponent(time)
                            .addComponent(tabletype)
                            .addComponent(tableid, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addGroup(tableInternalFrameLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton1)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        tableInternalFrameLayout.setVerticalGroup(
            tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableInternalFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tabletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(tableInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberofitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tableInternalFrame.setBounds(0, 0, 400, 320);
        jDesktopPane1.add(tableInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        helpInternalFrame.setTitle("Help");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("this is a bar program");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout helpInternalFrameLayout = new javax.swing.GroupLayout(helpInternalFrame.getContentPane());
        helpInternalFrame.getContentPane().setLayout(helpInternalFrameLayout);
        helpInternalFrameLayout.setHorizontalGroup(
            helpInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        helpInternalFrameLayout.setVerticalGroup(
            helpInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        helpInternalFrame.setBounds(0, 30, 340, 230);
        jDesktopPane1.add(helpInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        helpInternalFrame.getAccessibleContext().setAccessibleName("Help Frame");

        AdditemInternalFrame.setTitle("Add item");

        jLabel5.setText("Item name");

        jLabel6.setText("Item price");

        itemprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempriceActionPerformed(evt);
            }
        });

        jLabel7.setText("Item type");

        itemtypecombo.setEditable(true);
        itemtypecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item christmas", "Item with discount", "Items in offer", "Simple Item" }));
        itemtypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtypecomboActionPerformed(evt);
            }
        });

        jButton2.setText("Add item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdditemInternalFrameLayout = new javax.swing.GroupLayout(AdditemInternalFrame.getContentPane());
        AdditemInternalFrame.getContentPane().setLayout(AdditemInternalFrameLayout);
        AdditemInternalFrameLayout.setHorizontalGroup(
            AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                        .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                            .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemprice, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(itemtypecombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 155, Short.MAX_VALUE)
                                    .addComponent(itemname, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                    .addComponent(jLabel7)
                    .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        AdditemInternalFrameLayout.setVerticalGroup(
            AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(AdditemInternalFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(itemtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(AdditemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(43, 43, 43))
        );

        AdditemInternalFrame.setBounds(0, 0, 287, 373);
        jDesktopPane1.add(AdditemInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setViewportView(itemsintable);

        Removeitem.setText("Remove");
        Removeitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveitemActionPerformed(evt);
            }
        });

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeitemInternalFrameLayout = new javax.swing.GroupLayout(removeitemInternalFrame.getContentPane());
        removeitemInternalFrame.getContentPane().setLayout(removeitemInternalFrameLayout);
        removeitemInternalFrameLayout.setHorizontalGroup(
            removeitemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeitemInternalFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(removeitemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(removeitemInternalFrameLayout.createSequentialGroup()
                        .addComponent(Removeitem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        removeitemInternalFrameLayout.setVerticalGroup(
            removeitemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeitemInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(removeitemInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Removeitem)
                    .addComponent(jButton5))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        removeitemInternalFrame.setBounds(0, 0, 348, 351);
        jDesktopPane1.add(removeitemInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        waiterinfo.setColumns(20);
        waiterinfo.setEditable(false);
        waiterinfo.setRows(5);
        waiterinfo.setFocusable(false);
        jScrollPane4.setViewportView(waiterinfo);

        javax.swing.GroupLayout PrintInfoInternalFrameLayout = new javax.swing.GroupLayout(PrintInfoInternalFrame.getContentPane());
        PrintInfoInternalFrame.getContentPane().setLayout(PrintInfoInternalFrameLayout);
        PrintInfoInternalFrameLayout.setHorizontalGroup(
            PrintInfoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintInfoInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        PrintInfoInternalFrameLayout.setVerticalGroup(
            PrintInfoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintInfoInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        PrintInfoInternalFrame.setBounds(0, 0, 432, 392);
        jDesktopPane1.add(PrintInfoInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 480, 380);

        FileMenu.setText("File");

        jMenu5.setText("New Table");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        tableEmployeeMenuItem.setText("Table employee");
        tableEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(tableEmployeeMenuItem);

        tableCompanyMenuItem.setText("Table company");
        tableCompanyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableCompanyMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(tableCompanyMenuItem);

        tableFidelityMenuItem.setText("Table fidelity");
        tableFidelityMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableFidelityMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(tableFidelityMenuItem);

        simpletable.setText("Simple table");
        simpletable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpletableActionPerformed(evt);
            }
        });
        jMenu5.add(simpletable);

        FileMenu.add(jMenu5);

        numberoftables.setText("Overall number of tables for the waiter");
        numberoftables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberoftablesActionPerformed(evt);
            }
        });
        FileMenu.add(numberoftables);

        totalamount.setText("Total amount of all tables for the waiter");
        totalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalamountActionPerformed(evt);
            }
        });
        FileMenu.add(totalamount);

        jMenuBar1.add(FileMenu);

        helpMenu.setText("Help");
        helpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMenuMousePressed(evt);
            }
        });
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(helpMenu);

        DataMenu.setText("Data");

        load.setText("Load data");
        load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadMouseClicked(evt);
            }
        });
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        DataMenu.add(load);

        save.setText("Save data");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        DataMenu.add(save);

        jMenuBar1.add(DataMenu);

        PrintInfoMenu.setText("Print info");
        PrintInfoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrintInfoMenuMousePressed(evt);
            }
        });
        PrintInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintInfoMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(PrintInfoMenu);

        ExitMenu.setText("Exit");
        ExitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMenuMousePressed(evt);
            }
        });
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(ExitMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void numberoftablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberoftablesActionPerformed
JOptionPane.showMessageDialog(this, "Total number of tables for a waiter is " + totalnumberoftables());
}//GEN-LAST:event_numberoftablesActionPerformed

private void totalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalamountActionPerformed
JOptionPane.showMessageDialog(this, "Total amount of all tables for a waiter is  " + totalamountofalltables());
}//GEN-LAST:event_totalamountActionPerformed

private void tableEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableEmployeeMenuItemActionPerformed
        hideAllFrames();
        tableInternalFrame.setVisible(true);    
        currenttable = new tableEmployee(currentuser);
        
       
        tablelist.add(currenttable);
        tableid.setText(""+currenttable.getTableId());
        tabletype.setText("table employee");
        time.setText(currenttable.getTime());
        numberofitems.setText(""+currenttable.getItemList().size());
        
}//GEN-LAST:event_tableEmployeeMenuItemActionPerformed

private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
System.exit(1);
}//GEN-LAST:event_ExitMenuActionPerformed

private void PrintInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintInfoMenuActionPerformed

}//GEN-LAST:event_PrintInfoMenuActionPerformed

private void tableFidelityMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableFidelityMenuItemActionPerformed
// TODO add your handling code here:
    hideAllFrames();
        tableInternalFrame.setVisible(true);    
        currenttable = new tableFidelity(currentuser);
        
        
        tablelist.add(currenttable);
        tableid.setText(""+currenttable.getTableId());
        tabletype.setText("Table Fidelity");
        time.setText(currenttable.getTime());
        numberofitems.setText(""+currenttable.getItemList().size());
}//GEN-LAST:event_tableFidelityMenuItemActionPerformed

private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
    hideAllFrames();
    helpInternalFrame.setVisible(true);
}//GEN-LAST:event_helpMenuActionPerformed

private void tableCompanyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableCompanyMenuItemActionPerformed
        hideAllFrames();
        tableInternalFrame.setVisible(true);    
        currenttable = new tableCompany(currentuser);
        
        tablelist.add(currenttable);
        tableid.setText(""+currenttable.getTableId());
        tabletype.setText("Table company");
        time.setText(currenttable.getTime());
        numberofitems.setText(""+currenttable.getItemList().size());
        //TODO add your handling code here:
}//GEN-LAST:event_tableCompanyMenuItemActionPerformed

private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu5ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
tableInternalFrame.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_timeActionPerformed

private void jDesktopPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentHidden
// TODO add your handling code here:
}//GEN-LAST:event_jDesktopPane1ComponentHidden

private void jDesktopPane1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentMoved
// TODO add your handling code here:
}//GEN-LAST:event_jDesktopPane1ComponentMoved

private void helpMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuMousePressed
        hideAllFrames();
        helpInternalFrame.setVisible(true); 
    // TODO add your handling code here:
}//GEN-LAST:event_helpMenuMousePressed

private void ExitMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuMousePressed
    System.exit(1);
    // TODO add your handling code here:
}//GEN-LAST:event_ExitMenuMousePressed

private void additemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemActionPerformed
hideAllFrames();
AdditemInternalFrame.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_additemActionPerformed

private void itempriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempriceActionPerformed

}//GEN-LAST:event_itempriceActionPerformed

private void itemtypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtypecomboActionPerformed


// TODO add your handling code here:
}//GEN-LAST:event_itemtypecomboActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Item it = null;
ItemChristmas it1 = null;
Itemsinoffer it2 = null;
Itemwithdiscount it3 = null;
String name = "";
double price = 0.0;
    
        try{
            if(itemname.getText().equals("") || itemprice.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Enter the necessary data");
            else
            {
                name = itemname.getText().toString();
                price = Double.parseDouble(itemprice.getText().toString());
                if("Simple Item".equals(itemtypecombo.getSelectedItem().toString()))
                {    
                        it = new Item(name,price);
                        currenttable.addItemInTable(it);
                        
                        numberofitems.setText(""+currenttable.getItemList().size());
                }
                else if("Item christmas".equals(itemtypecombo.getSelectedItem().toString()))
                {
                    it1 = new ItemChristmas(name, price);
                    currenttable.addItemInTable(it1);
                    
                    numberofitems.setText(""+currenttable.getItemList().size());
                }
                else if("Item with discount".equals(itemtypecombo.getSelectedItem().toString()))
                {
                    it3 = new Itemwithdiscount(name, price);
                    currenttable.addItemInTable(it3);
                    
                    numberofitems.setText(""+currenttable.getItemList().size());
                }
                else if("Items in offer".equals(itemtypecombo.getSelectedItem().toString()))
                {
                    it2 = new Itemsinoffer(name, price);
                    currenttable.addItemInTable(it2);
                       
                        numberofitems.setText(""+currenttable.getItemList().size());
                }

            
            numberofitems.setText(""+currenttable.getItemList().size());
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Invalid input!");
        }

         
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
AdditemInternalFrame.setVisible(false);
tableInternalFrame.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void RemoveitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveitemActionPerformed
        
    if( itemsintable.getSelectedIndex() < 0 )
            return;
    
        currenttable.getItemList().remove(itemsintable.getSelectedIndex());
        itemsintable.setListData(currenttable.getItemList().toArray());
        

        numberofitems.setText(""+currenttable.getItemList().size());
// TODO add your handling code here:
}//GEN-LAST:event_RemoveitemActionPerformed

private void removeitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemActionPerformed
hideAllFrames();
removeitemInternalFrame.setVisible(true);
// TODO add your handling code here:
}//GEN-LAST:event_removeitemActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
removeitemInternalFrame.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

private void PrintInfoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintInfoMenuMousePressed
int userid = 0;
       
       try{
           
            String u = JOptionPane.showInputDialog(this, "Enter the waiter ID: ");
            userid = Integer.parseInt(u);
            //show info frame
            PrintInfoInternalFrame.setVisible(true);

            
            waiterinfo.setText("");
            for (Table t : tablelist) {
              if(t.getUser().getUserId() == userid){
                 waiterinfo.append(t.toString() + "\n");
              }
              else
              {
                  JOptionPane.showMessageDialog(this, "You entered the wrong ID");
                  PrintInfoInternalFrame.setVisible(false);
                  
              }
           }
            
        }catch(Exception e){
        }// TODO add your handling code here:
}//GEN-LAST:event_PrintInfoMenuMousePressed

private void tableinfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableinfoMousePressed

        JOptionPane.showMessageDialog(this, "Current table info: " + currenttable.toString());// TODO add your handling code here:
}//GEN-LAST:event_tableinfoMousePressed

private void tableinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableinfoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tableinfoActionPerformed

private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
JFileChooser c = new JFileChooser();
        c.showSaveDialog(this);

       
        File file = c.getSelectedFile();

        
        if( file == null ){
            return;
        }

        
        try{
            ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(file));
            
            output.writeObject(tablelist);
            output.close();
        }catch(Exception ex){
          
        }
        // TODO add your handling code here:
}//GEN-LAST:event_saveActionPerformed

private void loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadMouseClicked

    // TODO add your handling code here:
}//GEN-LAST:event_loadMouseClicked

private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);

        //get the selected file
        File file = chooser.getSelectedFile();

        //if no file selected
        if( file == null ){
            return;
        }

        //read in the file
        try{
            ObjectInputStream input = new ObjectInputStream(new FileInputStream(file));
            //read in all the list of baskets
            tablelist = (ArrayList<Table>)input.readObject();
            
            input.close();
        }catch(Exception ex){
          
        }// TODO add your handling code here:
}//GEN-LAST:event_loadActionPerformed

private void simpletableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpletableActionPerformed
hideAllFrames();
        tableInternalFrame.setVisible(true);    
        currenttable = new tableCompany(currentuser);
        
       
        tablelist.add(currenttable);
        tableid.setText(""+currenttable.getTableId());
        tabletype.setText("Simple table");
        time.setText(currenttable.getTime());
        numberofitems.setText(""+currenttable.getItemList().size());
    // TODO add your handling code here:
}//GEN-LAST:event_simpletableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login(new mainbar()).setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame AdditemInternalFrame;
    private javax.swing.JMenu DataMenu;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JInternalFrame PrintInfoInternalFrame;
    private javax.swing.JMenu PrintInfoMenu;
    private javax.swing.JButton Removeitem;
    private javax.swing.JMenu addcustomer;
    private javax.swing.JMenuItem additem;
    private javax.swing.JMenuItem companycustomer;
    private javax.swing.JMenuItem customeremployee;
    private javax.swing.JInternalFrame helpInternalFrame;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemprice;
    private javax.swing.JList itemsintable;
    private javax.swing.JComboBox itemtypecombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem load;
    private javax.swing.JMenuItem loyalcustomer;
    private javax.swing.JTextField numberofitems;
    private javax.swing.JMenuItem numberoftables;
    private javax.swing.JMenuItem removeitem;
    private javax.swing.JInternalFrame removeitemInternalFrame;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem simplecustomer;
    private javax.swing.JMenuItem simpletable;
    private javax.swing.JMenuItem tableCompanyMenuItem;
    private javax.swing.JMenuItem tableEmployeeMenuItem;
    private javax.swing.JMenuItem tableFidelityMenuItem;
    private javax.swing.JInternalFrame tableInternalFrame;
    private javax.swing.JTextField tableid;
    private javax.swing.JMenu tableinfo;
    private javax.swing.JTextField tabletype;
    private javax.swing.JTextField time;
    private javax.swing.JMenuItem totalamount;
    private javax.swing.JTextArea waiterinfo;
    // End of variables declaration//GEN-END:variables
}
